97 updates (#37)
* Updated templates with latest readiness logic
* Updated templates for broker 9.7 + documentation fixes

diff --git a/templates/eventbroker_singlenode_template.yaml b/templates/eventbroker_singlenode_template.yaml
--- a/templates/eventbroker_singlenode_template.yaml
+++ b/templates/eventbroker_singlenode_template.yaml
@@ -37,22 +37,26 @@ objects:
         export logging_debug_output=all
         export system_scaling_maxconnectioncount="100"
 
-    config-sync-check.sh: |-
+    setup-config-sync.sh: |-
         #!/bin/bash
         exit 0
 
 
     readiness_check.sh: |-
       #!/bin/bash
+      LOG_FILE=/usr/sw/var/k8s_readiness_check.log # STDOUT/STDERR goes to k8s event logs but gets cleaned out eventually. This will also persist it.
+      tail -n 1000 ${LOG_FILE} > ${LOG_FILE}.tmp; mv -f ${LOG_FILE}.tmp ${LOG_FILE} || :  # Limit logs size
+      exec > >(tee -a ${LOG_FILE}) 2>&1
 
       # Function to set Kubernetes metadata labels
       set_label () {
         #Prevent overdriving Kubernetes infra, don't set activity state to same as previous state
         previous_state=`cat $3`
         if [ "${2}" = "${previous_state}" ]; then
-          #echo "`date` INFO: ${APP}-Current and Previous state match, not updating label"
+          #echo "`date` INFO: ${APP}-Current and Previous state match (${2}), not updating label"
           :
         else
+          echo "`date` INFO: ${APP}-Updating label from `cat ${3}` to ${2}"
           echo ${2} > ${3}
           echo "[{\"op\": \"add\", \"path\": \"/metadata/labels/${1}\", \"value\": \"${2}\" }]" > /tmp/patch_label.json
           K8S=https://kubernetes.default.svc.cluster.local:$KUBERNETES_SERVICE_PORT
@@ -70,10 +74,11 @@ objects:
               echo "`date` ERROR: ${APP}-Unable to update pod label, check access from pod to K8s API or RBAC authorization" >&2
               exit 1
             fi
+            echo "`date` INFO: ${APP}-Failed to update label from ${3} to ${2}, retrying"
           fi
         fi
       }
-      # note that there are no re-tries here, if check fails the return not ready.
+      # note that there are no re-tries here, if check fails then return not ready.
       APP=`basename "$0"`
       state_file=/tmp/activity_state
       if [ ! -f ${state_file} ]; then  # State file not found, creating
@@ -84,18 +89,20 @@ objects:
       
       case "${health_result}" in
         "200")
-          echo "`date` INFO: ${APP}-nonHA Message Router is Active and Healthy"
+          if [[ $(cat $state_file) = "false" ]]; then echo "`date` INFO: ${APP}-nonHA Event Broker health check reported 200, message spool is up"; fi
           set_label "active" "true" $state_file
           exit 0
           ;;
         "503")
-          echo "`date` INFO: ${APP}-nonHA Message Router message spool is down"
+          if [[ $(cat $state_file) = "true" ]]; then echo "`date` INFO: ${APP}-nonHA Event Broker health check reported 503, message spool is down"; fi
           set_label "active" "false" $state_file
+          # Fail readiness check
           exit 1
           ;;
-        "")
-          echo "`date` WARN: ${APP}-Unable to determine config role, failing readiness check"
+        *)
+          echo "`date` WARN: ${APP}-nonHA Event Broker health check reported ${health_result}"
           set_label "active" "false" $state_file
+          # Fail readiness check
           exit 1
       esac
 
@@ -138,7 +145,7 @@ objects:
           echo  '<returnInfo><errorInfo>missing parameter</errorInfo></returnInfo>'
           exit 1
         fi
-        if [ `curl --write-out '%{http_code}' --silent --output /dev/null -u ${name}:${password} ${url}` != "200" ] ; then
+        if [ `curl --write-out '%{http_code}' --silent --output /dev/null -u ${name}:${password} ${url} -d "<rpc><show><version/></show></rpc>"` != "200" ] ; then
           echo  "<returnInfo><errorInfo>management host is not responding</errorInfo></returnInfo>"
           exit 1
         fi
@@ -297,11 +304,11 @@ objects:
           imagePullPolicy: IfNotPresent
           resources:
             requests:
-              cpu: "0.2"
-              memory: 0.8Gi
+              cpu: "2"
+              memory: 3.4Gi
             limits:
-              cpu: "1"
-              memory: 2Gi
+              cpu: "2"
+              memory: 3.4Gi
           livenessProbe:
             tcpSocket:
               port: 8080
@@ -329,7 +336,7 @@ objects:
              source /mnt/disks/solace/init.sh
              # not using postinstall hooks because of order dependencies
              # launch config check then PubSub+ so VCMR can provide return code
-             nohup /mnt/disks/solace/config-sync-check.sh &
+             nohup /mnt/disks/solace/setup-config-sync.sh &
              /usr/sbin/boot.sh
 
           lifecycle:
@@ -369,6 +376,9 @@ objects:
           - name: data
             mountPath: /usr/sw/internalSpool/softAdb
             subPath: softAdb
+          # use this instead if using NFS:
+          #- name: soft-adb-ephemeral
+          #  mountPath: /usr/sw/internalSpool/softAdb
           ports:
           - containerPort: 2222
             protocol: TCP
@@ -404,6 +414,9 @@ objects:
           - name: dshm
             emptyDir:
               medium: Memory
+          # add this if using NFS (together with montPath changes for softADB
+          # - name: soft-adb-ephemeral
+          # emptyDir: {}
     volumeClaimTemplates:
     - metadata:
         name: data
