Initial template updates using dedicated ServiceAccounts for the deployment

diff --git a/templates/eventbroker_ha_template.yaml b/templates/eventbroker_ha_template.yaml
--- a/templates/eventbroker_ha_template.yaml
+++ b/templates/eventbroker_ha_template.yaml
@@ -2,26 +2,26 @@
 apiVersion: v1
 kind: Template
 metadata:
-  name: solace-messagebroker-ha-template
+  name: pubsubplus-eventbroker-ha-template
   annotations:
-    description: Deploys Solace Message Broker in an HA configuration using persistent storage
+    description: Deploys PubSub+ Event Broker in an HA configuration using persistent storage
 objects:
 
 - kind: Secret
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-secrets"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-secrets"
     labels:
       app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       app.kubernetes.io/name: pubsubplus
   type: Opaque
   data:
-    username_admin_password: "${MESSAGEBROKER_ADMIN_PASSWORD}"
+    username_admin_password: "${EVENTBROKER_ADMIN_PASSWORD}"
 
 - kind: ConfigMap
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
       app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       app.kubernetes.io/name: pubsubplus
@@ -46,7 +46,7 @@ objects:
         else
           namespace=default
         fi
-        service="${DEPLOYMENT_NAME}-solace"
+        service="${DEPLOYMENT_NAME}-pubsubplus"
         # Deal with the fact we cannot accept "-" in routre names
         service_name=$(echo ${service} | sed 's/-//g')
         export routername=$(echo $(hostname) | sed 's/-//g')
@@ -113,7 +113,7 @@ objects:
             sleep ${pause}
           done
           if [ ${count} -eq ${loop_guard} ]; then
-            echo "`date` ERROR: ${APP}-Solace Management API never came up"  >&2
+            echo "`date` ERROR: ${APP}-Broker Management API never came up"  >&2
             exit 1
           fi
 
@@ -180,7 +180,7 @@ objects:
                 -q "<rpc><admin><config-sync><${resync_step}><router/></${resync_step}></config-sync></admin></rpc>"
           /mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
                 -q "<rpc><admin><config-sync><${resync_step}><vpn-name>default</vpn-name></${resync_step}></config-sync></admin></rpc>"
-          echo "`date` INFO: ${APP}-Solace message broker bringup complete for this node."
+          echo "`date` INFO: ${APP}-PubSub+ message broker bringup complete for this node."
         fi # if not monitor
         exit 0
 
@@ -445,10 +445,18 @@ objects:
 #  parameters:
 #    type: gp2
 
+-  kind: ServiceAccount
+   apiVersion: v1
+   metadata:
+    name: "${DEPLOYMENT_NAME}-pubsubplus-sa"
+    labels:
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
+      app.kubernetes.io/name: pubsubplus #end gcp
+ 
 - kind: Role
   apiVersion: rbac.authorization.k8s.io/v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-podtagupdater"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-podtagupdater"
   rules:
   - apiGroups: [""] # "" indicates the core API group
     resources: ["pods"]
@@ -457,20 +465,19 @@ objects:
 - kind: RoleBinding
   apiVersion: rbac.authorization.k8s.io/v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-serviceaccounts-to-podtagupdater"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-serviceaccounts-to-podtagupdater"
   roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: Role
-    name: "${DEPLOYMENT_NAME}-solace-podtagupdater"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-podtagupdater"
   subjects:
-  - kind: Group
-    name: system:serviceaccounts
-    apiGroup: rbac.authorization.k8s.io
+  - kind: ServiceAccount
+    name: "${DEPLOYMENT_NAME}-pubsubplus-sa"
 
 - kind: Service
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-discovery"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-discovery"
     labels:
       app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       app.kubernetes.io/name: pubsubplus
@@ -496,7 +503,7 @@ objects:
 - kind: Service
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
       app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       app.kubernetes.io/name: pubsubplus #end gcp
@@ -555,7 +562,7 @@ objects:
 - kind: StatefulSet
   apiVersion: apps/v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
       app.kubernetes.io/name: pubsubplus
       app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
@@ -564,7 +571,7 @@ objects:
       matchLabels:
         app.kubernetes.io/name: pubsubplus
         app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
-    serviceName: "${DEPLOYMENT_NAME}-solace-discovery"
+    serviceName: "${DEPLOYMENT_NAME}-pubsubplus-discovery"
     replicas: 3
     podManagementPolicy: Parallel
     updateStrategy: 
@@ -575,9 +582,11 @@ objects:
           app.kubernetes.io/name: pubsubplus
           app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       spec:
+        serviceAccountName: {{ template "solace.serviceAccountName" . }}
+        terminationGracePeriodSeconds: 1200
         containers:
-        - name: solace
-          image: "${DOCKER_REGISTRY_URL}:${MESSAGEBROKER_IMAGE_TAG}"
+        - name: pubsubplus
+          image: "${DOCKER_REGISTRY_URL}:${EVENTBROKER_IMAGE_TAG}"
           imagePullPolicy: IfNotPresent
           resources:
             requests:
@@ -601,7 +610,7 @@ objects:
             privileged: false
           env:
           - name: STATEFULSET_NAME
-            value: "${DEPLOYMENT_NAME}-solace"
+            value: "${DEPLOYMENT_NAME}-pubsubplus"
           - name: STATEFULSET_NAMESPACE
             valueFrom:
               fieldRef:
@@ -612,10 +621,20 @@ objects:
            - |
              source /mnt/disks/solace/init.sh
              # not using postinstall hooks because of order dependencies
-             # launch config check then Solace so VCMR can provide return code
+             # launch config check then PubSub+ so VCMR can provide return code
              nohup /mnt/disks/solace/config-sync-check.sh &
              /usr/sbin/boot.sh
 
+          lifecycle:
+            preStop:
+              exec:
+                command:
+                 - bash
+                 - "-ec"
+                 - |
+                   while ! pgrep solacedaemon ; do sleep 1; done
+                   killall solacedaemon; 
+                   while [ ! -d /usr/sw/var/db.upgrade ]; do sleep 1; done;
           volumeMounts:
           - name: config-map
             mountPath: /mnt/disks/solace
@@ -669,11 +688,11 @@ objects:
         volumes:
           - name: config-map
             configMap:
-              name: "${DEPLOYMENT_NAME}-solace"
+              name: "${DEPLOYMENT_NAME}-pubsubplus"
               defaultMode: 0755
           - name: secrets
             secret:
-              secretName: "${DEPLOYMENT_NAME}-solace-secrets"
+              secretName: "${DEPLOYMENT_NAME}-pubsubplus-secrets"
               defaultMode: 0400
           - name: dshm
             emptyDir:
@@ -688,11 +707,11 @@ objects:
         accessModes: [ "ReadWriteOnce" ]
         resources:
           requests:
-            storage: "${MESSAGEBROKER_STORAGE_SIZE}"
+            storage: "${EVENTBROKER_STORAGE_SIZE}"
 
 parameters:
   - name: DEPLOYMENT_NAME
-    displayName: Solace Message Broker Deployment Name
+    displayName: PubSub+ Event Broker Deployment Name
     description: The prefix to use for object names
     generate: expression
     from: '[A-Z0-9]{8}'
@@ -700,21 +719,21 @@ parameters:
     required: true
   - name: DOCKER_REGISTRY_URL
     displayName: Docker Registry URL
-    description: The Docker registry URL for the registry containing the Solace Message Broker docker image
+    description: The Docker registry URL for the registry containing the PubSub+ Event Broker docker image
     value: solace/solace-pubsub-standard
     required: true
-  - name: MESSAGEBROKER_IMAGE_TAG
-    displayName: Solace Message Broker Docker Image Tag
-    description: The Docker image tag for the Solace Message Broker docker image from your Docker registry
+  - name: EVENTBROKER_IMAGE_TAG
+    displayName: PubSub+ Event Broker Docker Image Tag
+    description: The Docker image tag for the PubSub+ Event Broker docker image from your Docker registry
     value: latest
     required: true
-  - name: MESSAGEBROKER_ADMIN_PASSWORD
-    displayName: Base64 encoded password for Solace username 'admin'
-    description: The Message Broker 'admin' user's password (base64 encoded).  This Solace OpenShift template will create an administrative user with username 'admin' with specified password.
+  - name: EVENTBROKER_ADMIN_PASSWORD
+    displayName: Base64 encoded password for PubSub+ username 'admin'
+    description: The Event Broker 'admin' user's password (base64 encoded).  This PubSub+ OpenShift template will create an administrative user with username 'admin' with specified password.
     value: "cEBzc3cwcmQ=" # password 'p@ssw0rd'
     required: true
-  - name: MESSAGEBROKER_STORAGE_SIZE
-    displayName: Solace Message Broker Persistent Storage Disk Size
-    description: The size in gigabytes for a Message Broker Pod's persistent volume (with suffix 'Gi'), example 30Gi for 30 gigabytes
+  - name: EVENTBROKER_STORAGE_SIZE
+    displayName: PubSub+ Event Broker Persistent Storage Disk Size
+    description: The size in gigabytes for a Event Broker Pod's persistent volume (with suffix 'Gi'), example 30Gi for 30 gigabytes
     value: 30Gi
     required: true
