Security enhancements (#31)
* Update templates to sync with latest solace-kubernetes-quickstart,
also set default to LA release

* Updated Helm version to 2.14, in sync with Kubernetes quickstart

* Updated readme about the EA load version available from Docker Hub

* Doc enhancements for Minishift

diff --git a/templates/messagebroker_singlenode_template.yaml b/templates/messagebroker_singlenode_template.yaml
--- a/templates/messagebroker_singlenode_template.yaml
+++ b/templates/messagebroker_singlenode_template.yaml
@@ -14,7 +14,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.3.0
+      chart: solace-1.0.1
       app: solace
   type: Opaque
   data:
@@ -27,7 +27,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.3.0
+      chart: solace-1.0.1
       app: solace
   data:
     init.sh: |-
@@ -38,8 +38,8 @@ objects:
         export service_webtransport_port='60080'
         export service_webtransport_tlsport='60443'
         export service_semp_tlsport='60943'
-        export logging_debug_output=stdout
-        export system_scaling_maxconnectioncount="1000"
+        export logging_debug_output=all
+        export system_scaling_maxconnectioncount="100"
 
     config-sync-check.sh: |-
         #!/bin/bash
@@ -54,27 +54,32 @@ objects:
         #Prevent overdriving Kubernetes infra, don't set activity state to same as previous state
         previous_state=`cat $3`
         if [ "${2}" = "${previous_state}" ]; then
-          echo "`date` INFO: ${APP}-Current and Previous state match, not updating label"
+          #echo "`date` INFO: ${APP}-Current and Previous state match, not updating label"
+          :
         else
           echo ${2} > ${3}
           echo "[{\"op\": \"add\", \"path\": \"/metadata/labels/${1}\", \"value\": \"${2}\" }]" > /tmp/patch_label.json
+          K8S=https://kubernetes.default.svc.cluster.local:$KUBERNETES_SERVICE_PORT
           KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
-          curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" --request PATCH --data "$(cat /tmp/patch_label.json)" \
-              -H "Content-Type:application/json-patch+json" \
-              https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/$STATEFULSET_NAMESPACE/pods/$HOSTNAME
+          CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+          NAMESPACE=$(</var/run/secrets/kubernetes.io/serviceaccount/namespace)
+          if ! curl -sS --output /dev/null --cacert $CACERT --connect-timeout 5 \
+              --request PATCH --data "$(cat /tmp/patch_label.json)" \
+              -H "Authorization: Bearer $KUBE_TOKEN" -H "Content-Type:application/json-patch+json" \
+              $K8S/api/v1/namespaces/$NAMESPACE/pods/$HOSTNAME ; then
+            echo "`date` ERROR: ${APP}-Unable to update pod label, check access from pod to K8s API or RBAC authorization" >&2
+            exit 1
+          fi
         fi
       }
 
       # note that there are no re-tries here, if check fails the return not ready.
       APP=`basename "$0"`
-
-      password=`cat /mnt/disks/secrets/username_admin_password`
       state_file=/tmp/activity_state
-      if [ ! -f ${state_file} ]; then
-        echo "State file not found, creating!"
-        echo "false" > ${state_file}
+      if [ ! -f ${state_file} ]; then  # State file not found, creating
+        echo "unknown" > ${state_file}
       fi
-
+      # nonHA config
       health_result=`curl -s -o /dev/null -w "%{http_code}"  http://localhost:5550/health-check/guaranteed-active`
       
       case "${health_result}" in
@@ -126,50 +131,53 @@ objects:
         shift $((OPTIND-1))
         [ "$1" = "--" ] && shift
         verbose=1
-        echo "`date` INFO: ${APP}-${script_name}: count_search=${count_search} ,name=${name} ,password=xxx query=${query} \
-                    ,url=${url} ,value_search=${value_search} ,Leftovers: $@" >&2
+        #echo "`date` INFO: ${APP}-${script_name}: count_search=${count_search} ,name=${name} ,password=xxx query=${query} \
+        #            ,url=${url} ,value_search=${value_search} ,Leftovers: $@" >&2
         if [[ ${url} = "" || ${name} = "" || ${password} = "" || ${query} = "" ]]; then
-            echo "`date` ERROR: ${APP}-${script_name}: url, name, password and query are madatory fields" >&2
-            echo  '{"errorInfo":"missing parameter"}'
-            exit 1
-          fi
+          echo "`date` ERROR: ${APP}-${script_name}: url, name, password and query are madatory fields" >&2
+          echo  '<returnInfo><errorInfo>missing parameter</errorInfo></returnInfo>'
+          exit 1
+        fi
+        if [ `curl --write-out '%{http_code}' --silent --output /dev/null -u ${name}:${password} ${url}` != "200" ] ; then
+          echo  "<returnInfo><errorInfo>management host is not responding</errorInfo></returnInfo>"
+          exit 1
+        fi
         query_response=`curl -sS -u ${name}:${password} ${url} -d "${query}"`
         # Validate first char of response is "<", otherwise no hope of being valid xml
         if [[ ${query_response:0:1} != "<" ]] ; then 
-          echo "`date` ERROR: ${APP}-${script_name}: Query failed, non-xml response -${query_response}-" >&2
+          echo  "<returnInfo><errorInfo>no valid xml returned</errorInfo></returnInfo>"
           exit 1
         fi
         query_response_code=`echo $query_response | xmllint -xpath 'string(/rpc-reply/execute-result/@code)' -`
 
         if [[ -z ${query_response_code} && ${query_response_code} != "ok" ]]; then
-            echo "`date` ERROR: ${APP}-${script_name}: Query failed, bad return code -${query_response}-" >&2
-            echo  "{\"errorInfo\":\"query failed -${query_response_code}-\"}"
+            echo  "<returnInfo><errorInfo>query failed -${query_response_code}-</errorInfo></returnInfo>"
             exit 1
         fi
-        echo "`date` INFO: ${APP}-${script_name}: Query passed ${query_response_code}" >&2
+        #echo "`date` INFO: ${APP}-${script_name}: query passed ${query_response_code}" >&2
         if [[ ! -z $value_search ]]; then
             value_result=`echo $query_response | xmllint -xpath "string($value_search)" -`
-            echo "`date` INFO: ${APP}-${script_name}: Value search $value_search returned ${value_result}" >&2
-            echo  "{\"errorInfo\":\"\",\"valueSearchResult\":\"${value_result}\"}"
+            echo  "<returnInfo><errorInfo></errorInfo><valueSearchResult>${value_result}</valueSearchResult></returnInfo>"
             exit 0
         fi
         if [[ ! -z $count_search ]]; then
             count_line=`echo $query_response | xmllint -xpath "$count_search" -`
             count_string=`echo $count_search | cut -d '"' -f 2`
             count_result=`echo ${count_line} | tr "><" "\n" | grep -c ${count_string}`
-            echo -e "`date` INFO: ${APP}-${script_name}: \n\t count search: $count_search \n\t count_line: ${count_line} \n\t count_string: ${count_string} \n\t count_result: ${count_result}" >&2
-            echo  "{\"errorInfo\":\"\",\"countSearchResult\":${count_result}}"
+            echo  "<returnInfo><errorInfo></errorInfo><countSearchResult>${count_result}</countSearchResult></returnInfo>"
             exit 0
         fi
 
-- kind: StorageClass
-  apiVersion: storage.k8s.io/v1
-  metadata:
-    name: "${DEPLOYMENT_NAME}-standard"
-  provisioner: kubernetes.io/aws-ebs
-  parameters:
-  #Default don't set zone or zones, allow k8s to strip across active zones
-    type: gp2
+# Uncomment if using provider-specific StorageClass
+# Also uncomment further down at volumeClaimTemplates
+# This is an example for aws
+#- kind: StorageClass
+#  apiVersion: storage.k8s.io/v1
+#  metadata:
+#    name: "${DEPLOYMENT_NAME}-standard"
+#  provisioner: kubernetes.io/aws-ebs
+#  parameters:
+#    type: gp2
 
 - kind: Service
   apiVersion: v1
@@ -178,7 +186,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.3.0
+      chart: solace-1.0.1
       app: solace
     annotations:
       service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
@@ -198,7 +206,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.3.0
+      chart: solace-1.0.1
       app: solace #end gcp
   spec:
     type: LoadBalancer
@@ -208,13 +216,21 @@ objects:
       protocol: TCP
       name: ssh
     - port: 8080
-      targetPort: 8080
+      targetPort: 
       protocol: TCP
       name: semp
     - port: 55555
-      targetPort: 55555
+      targetPort: 
       protocol: TCP
       name: smf
+    - port: 55003
+      targetPort: 
+      protocol: TCP
+      name: smfcompr
+    - port: 55443
+      targetPort: 
+      protocol: TCP
+      name: smftls
     - port: 943
       targetPort: 60943
       protocol: TCP
@@ -238,12 +254,15 @@ objects:
     name: "${DEPLOYMENT_NAME}-solace"
     labels:
       app: solace
-      chart: solace-0.3.0
+      chart: solace-1.0.1
       release: "${DEPLOYMENT_NAME}"
       heritage: Tiller
   spec:
     serviceName: "${DEPLOYMENT_NAME}-solace-discovery"
     replicas: 1
+    podManagementPolicy: Parallel
+    updateStrategy: 
+      type: RollingUpdate
     template:
       metadata:
         labels:
@@ -256,11 +275,11 @@ objects:
           imagePullPolicy: IfNotPresent
           resources:
             requests:
-              cpu: "1.2"
-              memory: 6.0Gi
+              cpu: "0.2"
+              memory: 0.8Gi
             limits:
-              cpu: "2"
-              memory: 7.5Gi
+              cpu: "1"
+              memory: 2Gi
           livenessProbe:
             tcpSocket:
               port: 8080
@@ -321,6 +340,7 @@ objects:
           - name: data
             mountPath: /var/lib/solace/diags
             subPath: diags
+          # only mount when not using nfs
           - name: data
             mountPath: /usr/sw/internalSpool/softAdb
             subPath: softAdb #end !nfs
@@ -330,6 +350,10 @@ objects:
           - containerPort: 8080
             protocol: TCP
           - containerPort: 55555
+            protocol: TCP
+          - containerPort: 55003
+            protocol: TCP
+          - containerPort: 55443
             protocol: TCP
           - containerPort: 60943
             protocol: TCP
@@ -353,7 +377,9 @@ objects:
     - metadata:
         name: data
       spec:
-        storageClassName: "${DEPLOYMENT_NAME}-standard"
+        # Uncomment if using provider-specific StorageClass
+        # Also uncomment StorageClass definition above
+        # storageClassName: "${DEPLOYMENT_NAME}-standard"
         accessModes: [ "ReadWriteOnce" ]
         resources:
           requests:
@@ -370,12 +396,12 @@ parameters:
   - name: DOCKER_REGISTRY_URL
     displayName: Docker Registry URL
     description: The Docker registry URL for the registry containing the Solace Message Broker docker image
-    value: docker_registry_url
+    value: solace/solace-pubsub-standard
     required: true
   - name: MESSAGEBROKER_IMAGE_TAG
     displayName: Solace Message Broker Docker Image Tag
     description: The Docker image tag for the Solace Message Broker docker image from your Docker registry
-    value: solace_messagebroker_image_tag
+    value: 9.4.0EA
     required: true
   - name: MESSAGEBROKER_ADMIN_PASSWORD
     displayName: Base64 encoded password for Solace username 'admin'
