OpenShift 3.7 updates (#22)
* Added support for OpenShift 3.7  ( 3.6 is deprecated ).
* Simplified and clarified deployment process
* Default to use Solace PubSub+ docker image from Docker Hub
* New helper scripts
* 3.9 support will come next

diff --git a/templates/messagebroker_singlenode_template.yaml b/templates/messagebroker_singlenode_template.yaml
--- a/templates/messagebroker_singlenode_template.yaml
+++ b/templates/messagebroker_singlenode_template.yaml
@@ -2,9 +2,9 @@
 apiVersion: v1
 kind: Template
 metadata:
-  name: solace-vmr-singlenode-template
+  name: solace-messagebroker-singlenode-template
   annotations:
-    description: Deploys Solace VMR in an Single Node configuration
+    description: Deploys Solace Message Broker in a Single Node configuration
 objects:
 
 - kind: Secret
@@ -14,11 +14,11 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.2.0
+      chart: solace-0.3.0
       app: solace
   type: Opaque
   data:
-    username_admin_password: "${VMR_ADMIN_PASSWORD}"
+    username_admin_password: "${MESSAGEBROKER_ADMIN_PASSWORD}"
 
 - kind: ConfigMap
   apiVersion: v1
@@ -27,7 +27,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.2.0
+      chart: solace-0.3.0
       app: solace
   data:
     init.sh: |-
@@ -64,97 +64,32 @@ objects:
 
       # note that there are no re-tries here, if check fails the return not ready.
       APP=`basename "$0"`
-      version=${1}
 
       password=`cat /mnt/disks/secrets/username_admin_password`
-      return_code=0
       state_file=/tmp/activity_state
       if [ ! -f ${state_file} ]; then
         echo "State file not found, creating!"
         echo "false" > ${state_file}
       fi
-      echo "`date` INFO: ${APP}-node oridinal"
-      IFS='-' read -ra host_array <<< $(hostname)
-      node_ordinal=${host_array[-1]}
-
-      if [ "${node_ordinal}" = "2" ]; then
-        echo "`date` INFO: ${APP}-Monitor node ready check"
-        # Note that when dealing with Monitor, only need to be concerned and readiness response.
-        # active label will always be "false"
-        echo "`date` INFO: ${APP}-For monitor node just check for 3 online nodes in group"
-        role_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
-                -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><group/></redundancy></show></rpc>" \
-                -c "/rpc-reply/rpc/show/redundancy/group-node/status[text() = \"Online\"]"`
-        if [ `echo ${role_results} | jq '.countSearchResult' -` -eq 3 ]; then
-          echo "`date` INFO: ${APP}-Monitor node is redundancy ready"
-          exit 0
-        else
-          echo "`date` INFO: ${APP}-Monitor node is not redundancy ready, result: ${role_results}"
-          exit 1
-        fi
-      fi # End Monitor Node
 
       health_result=`curl -s -o /dev/null -w "%{http_code}"  http://localhost:5550/health-check/guaranteed-active`
       
       case "${health_result}" in
         "200")
-           echo "`date` INFO: ${APP}-Message Router is Active and Healthy"
+          echo "`date` INFO: ${APP}-nonHA Message Router is Active and Healthy"
           set_label "active" "true" $state_file
           exit 0
           ;;
         "503")
+          echo "`date` INFO: ${APP}-nonHA Message Router message spool is down"
           set_label "active" "false" $state_file
-          if (( "$version" < 7 )); then
-           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, this is K8S 1.6 ready"
-           exit 0
-          else
-           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, further check required"
-          fi
+          exit 1
           ;;
         "")
-          echo "`date` WARN: ${APP}-Unable to deturmine config role, failing readiness check"
+          echo "`date` WARN: ${APP}-Unable to determine config role, failing readiness check"
           set_label "active" "false" $state_file
           exit 1
       esac
-       
-      echo "`date` INFO: ${APP}-Checking if Message Router is Standby"
-      case "${node_ordinal}" in
-        "0")
-          config_role="primary"
-          ;;
-        "1")
-          config_role="backup"
-          ;;
-      esac
-      online_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
-              -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><detail/></redundancy></show></rpc>" \
-              -v "/rpc-reply/rpc/show/redundancy/virtual-routers/${config_role}/status/activity[text()]"`
-      local_activity=`echo ${online_results} | jq '.valueSearchResult' -`
-      echo "`date` INFO: ${APP}-Local activity state is: ${local_activity}"
-      case "${local_activity}" in
-        "\"Local Active\"")
-          echo "`date` INFO: ${APP}-Redundancy is up locally Active"
-          # Set active label to "true"
-          set_label "active" "true" $state_file
-          # Pass readiness check
-          exit 0
-          ;;
-        "\"Mate Active\"")
-          echo "`date` INFO: ${APP}-Redundancy is up mate Active"
-          # Set active label to "false"
-          set_label "active" "false" $state_file
-          # Pass readiness check
-          exit 0
-          ;;
-        *)
-          echo "`date` WARN: ${APP}-Redundancy not up or not responding, failing readiness check"
-          # Set active label to "false"
-          set_label "active" "false" $state_file
-          # Fail readiness check
-          exit 1
-          ;;
-      esac
-
 
     semp_query.sh: |-
         #!/bin/bash
@@ -233,7 +168,6 @@ objects:
   #Default don't set zone or zones, allow k8s to strip across active zones
     type: gp2
 
-
 - kind: Service
   apiVersion: v1
   metadata:
@@ -241,7 +175,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.2.0
+      chart: solace-0.3.0
       app: solace
     annotations:
       service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
@@ -261,7 +195,7 @@ objects:
     labels:
       heritage: Tiller
       release: "${DEPLOYMENT_NAME}"
-      chart: solace-0.2.0
+      chart: solace-0.3.0
       app: solace #end gcp
   spec:
     type: LoadBalancer
@@ -286,7 +220,7 @@ objects:
     name: "${DEPLOYMENT_NAME}-solace"
     labels:
       app: solace
-      chart: solace-0.2.0
+      chart: solace-0.3.0
       release: "${DEPLOYMENT_NAME}"
       heritage: Tiller
   spec:
@@ -300,7 +234,7 @@ objects:
       spec:
         containers:
         - name: solace
-          image: "${DOCKER_REGISTRY_URL}:${VMR_IMAGE_TAG}"
+          image: "${DOCKER_REGISTRY_URL}:${MESSAGEBROKER_IMAGE_TAG}"
           imagePullPolicy: IfNotPresent
           resources:
             requests:
@@ -320,7 +254,7 @@ objects:
             exec:
               command:
               - /mnt/disks/solace/readiness_check.sh
-              - "6"
+              - "7"
           securityContext:
             privileged: true
             capabilities:
@@ -406,11 +340,11 @@ objects:
         accessModes: [ "ReadWriteOnce" ]
         resources:
           requests:
-            storage: "${VMR_STORAGE_SIZE}"
+            storage: "${MESSAGEBROKER_STORAGE_SIZE}"
 
 parameters:
   - name: DEPLOYMENT_NAME
-    displayName: Solace VMR Deployment Name
+    displayName: Solace Message Broker Deployment Name
     description: The prefix to use for object names
     generate: expression
     from: '[A-Z0-9]{8}'
@@ -418,21 +352,21 @@ parameters:
     required: true
   - name: DOCKER_REGISTRY_URL
     displayName: Docker Registry URL
-    description: The Docker registry URL for the registry containing the Solace VMR docker image
+    description: The Docker registry URL for the registry containing the Solace Message Broker docker image
     value: docker_registry_url
     required: true
-  - name: VMR_IMAGE_TAG
-    displayName: Solace VMR Docker Image Tag
-    description: The Docker image tag for the Solace VMR docker image from your Docker registry
-    value: solace_vmr_image_tag
+  - name: MESSAGEBROKER_IMAGE_TAG
+    displayName: Solace Message Broker Docker Image Tag
+    description: The Docker image tag for the Solace Message Broker docker image from your Docker registry
+    value: solace_messagebroker_image_tag
     required: true
-  - name: VMR_ADMIN_PASSWORD
+  - name: MESSAGEBROKER_ADMIN_PASSWORD
     displayName: Base64 encoded password for Solace username 'admin'
-    description: The VMR 'admin' user's password (base64 encoded).  This Solace OpenShift template will create an administrative user with username 'admin' with specified password.
+    description: The Message Broker 'admin' user's password (base64 encoded).  This Solace OpenShift template will create an administrative user with username 'admin' with specified password.
     value: "cEBzc3cwcmQ=" # password 'p@ssw0rd'
     required: true
-  - name: VMR_STORAGE_SIZE
-    displayName: Solace VMR Persistent Storage Disk Size
-    description: The size in gigabytes for a VMR Pod's persistent volume (with suffix 'Gi'), example 30Gi for 30 gigabytes
+  - name: MESSAGEBROKER_STORAGE_SIZE
+    displayName: Solace Message Broker Persistent Storage Disk Size
+    description: The size in gigabytes for a Message Broker Pod's persistent volume (with suffix 'Gi'), example 30Gi for 30 gigabytes
     value: 30Gi
     required: true
