Updated non-HA OpenShift template

diff --git a/templates/messagebroker_singlenode_template.yaml b/templates/messagebroker_singlenode_template.yaml
--- a/templates/messagebroker_singlenode_template.yaml
+++ b/templates/messagebroker_singlenode_template.yaml
@@ -10,12 +10,10 @@ objects:
 - kind: Secret
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-secrets"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-secrets"
     labels:
-      heritage: Tiller
-      release: "${DEPLOYMENT_NAME}"
-      chart: solace-1.0.1
-      app: solace
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
+      app.kubernetes.io/name: pubsubplus
   type: Opaque
   data:
     username_admin_password: "${MESSAGEBROKER_ADMIN_PASSWORD}"
@@ -23,12 +21,10 @@ objects:
 - kind: ConfigMap
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
-      heritage: Tiller
-      release: "${DEPLOYMENT_NAME}"
-      chart: solace-1.0.1
-      app: solace
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
+      app.kubernetes.io/name: pubsubplus
   data:
     init.sh: |-
       # export username_admin_passwordfilepath=/mnt/disks/secrets/username_admin_password
@@ -67,12 +63,16 @@ objects:
               --request PATCH --data "$(cat /tmp/patch_label.json)" \
               -H "Authorization: Bearer $KUBE_TOKEN" -H "Content-Type:application/json-patch+json" \
               $K8S/api/v1/namespaces/$NAMESPACE/pods/$HOSTNAME ; then
-            echo "`date` ERROR: ${APP}-Unable to update pod label, check access from pod to K8s API or RBAC authorization" >&2
-            exit 1
+            # Fall back to alternative method to update label
+            if ! curl -sSk --output /dev/null -H "Authorization: Bearer $KUBE_TOKEN" --request PATCH --data "$(cat /tmp/patch_label.json)" \
+              -H "Content-Type:application/json-patch+json" \
+              https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/$STATEFULSET_NAMESPACE/pods/$HOSTNAME ; then
+              echo "`date` ERROR: ${APP}-Unable to update pod label, check access from pod to K8s API or RBAC authorization" >&2
+              exit 1
+            fi
           fi
         fi
       }
-
       # note that there are no re-tries here, if check fails the return not ready.
       APP=`basename "$0"`
       state_file=/tmp/activity_state
@@ -125,7 +125,7 @@ objects:
             u)  url=$OPTARG
                 ;;
             v)  value_search=$OPTARG
-                ;;        
+                ;;
             esac
         done
         shift $((OPTIND-1))
@@ -144,7 +144,7 @@ objects:
         fi
         query_response=`curl -sS -u ${name}:${password} ${url} -d "${query}"`
         # Validate first char of response is "<", otherwise no hope of being valid xml
-        if [[ ${query_response:0:1} != "<" ]] ; then 
+        if [[ ${query_response:0:1} != "<" ]] ; then
           echo  "<returnInfo><errorInfo>no valid xml returned</errorInfo></returnInfo>"
           exit 1
         fi
@@ -179,35 +179,34 @@ objects:
 #  parameters:
 #    type: gp2
 
-- kind: Service
-  apiVersion: v1
+- kind: Role
+  apiVersion: rbac.authorization.k8s.io/v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace-discovery"
-    labels:
-      heritage: Tiller
-      release: "${DEPLOYMENT_NAME}"
-      chart: solace-1.0.1
-      app: solace
-    annotations:
-      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
-  spec:
-    ports:
-      - port: 8080
-        name: semp
-    clusterIP: None
-    selector:
-      app: solace
-      release: "${DEPLOYMENT_NAME}"
+    name: "${DEPLOYMENT_NAME}-pubsubplus-podtagupdater"
+  rules:
+  - apiGroups: [""] # "" indicates the core API group
+    resources: ["pods"]
+    verbs: ["patch"]
 
+- kind: RoleBinding
+  apiVersion: rbac.authorization.k8s.io/v1
+  metadata:
+    name: "${DEPLOYMENT_NAME}-pubsubplus-serviceaccounts-to-podtagupdater"
+  roleRef:
+    apiGroup: rbac.authorization.k8s.io
+    kind: Role
+    name: "${DEPLOYMENT_NAME}-pubsubplus-podtagupdater"
+  subjects:
+  - kind: Group
+    name: system:serviceaccounts
+    apiGroup: rbac.authorization.k8s.io
 - kind: Service
   apiVersion: v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
-      heritage: Tiller
-      release: "${DEPLOYMENT_NAME}"
-      chart: solace-1.0.1
-      app: solace #end gcp
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
+      app.kubernetes.io/name: pubsubplus #end gcp
   spec:
     type: LoadBalancer
     ports:
@@ -216,25 +215,25 @@ objects:
       protocol: TCP
       name: ssh
     - port: 8080
-      targetPort: 
+      targetPort: 8080
       protocol: TCP
       name: semp
-    - port: 55555
-      targetPort: 
-      protocol: TCP
-      name: smf
-    - port: 55003
-      targetPort: 
-      protocol: TCP
-      name: smfcompr
-    - port: 55443
-      targetPort: 
-      protocol: TCP
-      name: smftls
     - port: 943
       targetPort: 60943
       protocol: TCP
       name: semptls
+    - port: 55555
+      targetPort: 55555
+      protocol: TCP
+      name: smf
+    - port: 55003
+      targetPort: 55003
+      protocol: TCP
+      name: smfcomp
+    - port: 55443
+      targetPort: 55443
+      protocol: TCP
+      name: smftls
     - port: 80
       targetPort: 60080
       protocol: TCP
@@ -243,22 +242,36 @@ objects:
       targetPort: 60443
       protocol: TCP
       name: webtls
+    - port: 5672
+      targetPort: 5672
+      protocol: TCP
+      name: amqp
+    - port: 1883
+      targetPort: 1883
+      protocol: TCP
+      name: mqtt
+    - port: 9000
+      targetPort: 9000
+      protocol: TCP
+      name: rest
     selector:
-      app: solace
-      release: "${DEPLOYMENT_NAME}"
+      app.kubernetes.io/name: pubsubplus
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       active: "true"
 
 - kind: StatefulSet
-  apiVersion: apps/v1beta1
+  apiVersion: apps/v1
   metadata:
-    name: "${DEPLOYMENT_NAME}-solace"
+    name: "${DEPLOYMENT_NAME}-pubsubplus"
     labels:
-      app: solace
-      chart: solace-1.0.1
-      release: "${DEPLOYMENT_NAME}"
-      heritage: Tiller
+      app.kubernetes.io/name: pubsubplus
+      app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
   spec:
-    serviceName: "${DEPLOYMENT_NAME}-solace-discovery"
+    selector:
+      matchLabels:
+        app.kubernetes.io/name: pubsubplus
+        app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
+    serviceName: "${DEPLOYMENT_NAME}-pubsubplus-discovery"
     replicas: 1
     podManagementPolicy: Parallel
     updateStrategy: 
@@ -266,8 +279,8 @@ objects:
     template:
       metadata:
         labels:
-          app: solace
-          release: "${DEPLOYMENT_NAME}"
+          app.kubernetes.io/name: pubsubplus
+          app.kubernetes.io/instance: "${DEPLOYMENT_NAME}"
       spec:
         containers:
         - name: solace
@@ -291,26 +304,15 @@ objects:
             exec:
               command:
               - /mnt/disks/solace/readiness_check.sh
-              - "7"
           securityContext:
             privileged: false
-            capabilities:
-              add:
-                - IPC_LOCK
-                - SYS_NICE
           env:
           - name: STATEFULSET_NAME
-            value: "${DEPLOYMENT_NAME}-solace"
+            value: "${DEPLOYMENT_NAME}-pubsubplus"
           - name: STATEFULSET_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
-  # [TODO] not using correct method of finding ordinal until we bump min Kubernetes release above 1.8.1
-   #       - name: STATEFULSET_ORDINAL
-   #         valueFrom:
-   #           fieldRef:
-   #             fieldPath: metadata.annotations['annotationKey']
-
           command:
            - bash
            - "-ec"
@@ -347,11 +349,13 @@ objects:
           # only mount when not using nfs
           - name: data
             mountPath: /usr/sw/internalSpool/softAdb
-            subPath: softAdb #end !nfs
+            subPath: softAdb
           ports:
           - containerPort: 2222
             protocol: TCP
           - containerPort: 8080
+            protocol: TCP
+          - containerPort: 60943
             protocol: TCP
           - containerPort: 55555
             protocol: TCP
@@ -359,20 +363,26 @@ objects:
             protocol: TCP
           - containerPort: 55443
             protocol: TCP
-          - containerPort: 60943
-            protocol: TCP
+                                
+                         
           - containerPort: 60080
             protocol: TCP
           - containerPort: 60443
             protocol: TCP
+          - containerPort: 5672
+            protocol: TCP
+          - containerPort: 1883
+            protocol: TCP
+          - containerPort: 9000
+            protocol: TCP
         volumes:
           - name: config-map
             configMap:
-              name: "${DEPLOYMENT_NAME}-solace"
+              name: "${DEPLOYMENT_NAME}-pubsubplus"
               defaultMode: 0755
           - name: secrets
             secret:
-              secretName: "${DEPLOYMENT_NAME}-solace-secrets"
+              secretName: "${DEPLOYMENT_NAME}-pubsubplus-secrets"
               defaultMode: 0400
           - name: dshm
             emptyDir:
