simplify readiness check for non-HA config

diff --git a/templates/messagebroker_singlenode_template.yaml b/templates/messagebroker_singlenode_template.yaml
--- a/templates/messagebroker_singlenode_template.yaml
+++ b/templates/messagebroker_singlenode_template.yaml
@@ -64,97 +64,32 @@ objects:
 
       # note that there are no re-tries here, if check fails the return not ready.
       APP=`basename "$0"`
-      version=${1}
 
       password=`cat /mnt/disks/secrets/username_admin_password`
-      return_code=0
       state_file=/tmp/activity_state
       if [ ! -f ${state_file} ]; then
         echo "State file not found, creating!"
         echo "false" > ${state_file}
       fi
-      echo "`date` INFO: ${APP}-node oridinal"
-      IFS='-' read -ra host_array <<< $(hostname)
-      node_ordinal=${host_array[-1]}
-
-      if [ "${node_ordinal}" = "2" ]; then
-        echo "`date` INFO: ${APP}-Monitor node ready check"
-        # Note that when dealing with Monitor, only need to be concerned and readiness response.
-        # active label will always be "false"
-        echo "`date` INFO: ${APP}-For monitor node just check for 3 online nodes in group"
-        role_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
-                -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><group/></redundancy></show></rpc>" \
-                -c "/rpc-reply/rpc/show/redundancy/group-node/status[text() = \"Online\"]"`
-        if [ `echo ${role_results} | jq '.countSearchResult' -` -eq 3 ]; then
-          echo "`date` INFO: ${APP}-Monitor node is redundancy ready"
-          exit 0
-        else
-          echo "`date` INFO: ${APP}-Monitor node is not redundancy ready, result: ${role_results}"
-          exit 1
-        fi
-      fi # End Monitor Node
 
       health_result=`curl -s -o /dev/null -w "%{http_code}"  http://localhost:5550/health-check/guaranteed-active`
       
       case "${health_result}" in
         "200")
-           echo "`date` INFO: ${APP}-Message Router is Active and Healthy"
+          echo "`date` INFO: ${APP}-nonHA Message Router is Active and Healthy"
           set_label "active" "true" $state_file
           exit 0
           ;;
         "503")
+          echo "`date` INFO: ${APP}-nonHA Message Router message spool is down"
           set_label "active" "false" $state_file
-          if (( "$version" < 7 )); then
-           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, this is K8S 1.6 ready"
-           exit 0
-          else
-           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, further check required"
-          fi
+          exit 1
           ;;
         "")
-          echo "`date` WARN: ${APP}-Unable to deturmine config role, failing readiness check"
+          echo "`date` WARN: ${APP}-Unable to determine config role, failing readiness check"
           set_label "active" "false" $state_file
           exit 1
       esac
-       
-      echo "`date` INFO: ${APP}-Checking if Message Router is Standby"
-      case "${node_ordinal}" in
-        "0")
-          config_role="primary"
-          ;;
-        "1")
-          config_role="backup"
-          ;;
-      esac
-      online_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
-              -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><detail/></redundancy></show></rpc>" \
-              -v "/rpc-reply/rpc/show/redundancy/virtual-routers/${config_role}/status/activity[text()]"`
-      local_activity=`echo ${online_results} | jq '.valueSearchResult' -`
-      echo "`date` INFO: ${APP}-Local activity state is: ${local_activity}"
-      case "${local_activity}" in
-        "\"Local Active\"")
-          echo "`date` INFO: ${APP}-Redundancy is up locally Active"
-          # Set active label to "true"
-          set_label "active" "true" $state_file
-          # Pass readiness check
-          exit 0
-          ;;
-        "\"Mate Active\"")
-          echo "`date` INFO: ${APP}-Redundancy is up mate Active"
-          # Set active label to "false"
-          set_label "active" "false" $state_file
-          # Pass readiness check
-          exit 0
-          ;;
-        *)
-          echo "`date` WARN: ${APP}-Redundancy not up or not responding, failing readiness check"
-          # Set active label to "false"
-          set_label "active" "false" $state_file
-          # Fail readiness check
-          exit 1
-          ;;
-      esac
-
 
     semp_query.sh: |-
         #!/bin/bash
