Updated templates based on latest Solace Kubernetes QuickStart changes to fix bug where clients could not connect

diff --git a/templates/vmr_singleNode_template.yaml b/templates/vmr_singleNode_template.yaml
--- a/templates/vmr_singleNode_template.yaml
+++ b/templates/vmr_singleNode_template.yaml
@@ -16,16 +16,10 @@ objects:
       release: "${DEPLOYMENT_NAME}"
       chart: solace-0.2.0
       app: solace
-    annotations:
-      "helm.sh/hook": pre-install
-      "helm.sh/hook-weight": "5"
   type: Opaque
   data:
     username_admin_password: "${VMR_ADMIN_PASSWORD}"
-  MANIFEST:
 
-
-# Source: solace/templates/solaceConfigMap.yaml
 - kind: ConfigMap
   apiVersion: v1
   metadata:
@@ -48,29 +42,118 @@ objects:
         #!/bin/bash
         exit 0
 
+
     readiness_check.sh: |-
-        #!/bin/bash
-        APP=`basename "$0"`
-        IFS='-' read -ra host_array <<< $(hostname)
-        node_ordinal=${host_array[-1]}
-        password=`cat /mnt/disks/secrets/username_admin_password`
-        return_code=0
-        echo "`date` INFO: ${APP}-Getting POD name"
-        echo "`date` INFO: ${APP}-Performing readiness check"
-        echo "`date` INFO: ${APP}-Determining redundancy role"
-        echo "`date` INFO: ${APP}-Redundancy role is ${local_role}"
-        echo "`date` INFO: ${APP}-Redundancy state based on role should be ${role_state}"
-        echo "`date` INFO: ${APP}-Determining redundancy state"
-        echo "`date` INFO: ${APP}-Redundancy state is ${local_state}" 
-        if [ ${role_state} -eq ${local_state} ]; then
-          if [ ${local_state} -eq "local_active" ]; then
-            echo "`date` INFO: ${APP}-Setting redundancy_active label" 
-          fi
-          echo "`date` INFO: ${APP}-Setting return code READY for ${pod_name}"
+      #!/bin/bash
+
+      # Function to set Kubernetes metadata labels
+      set_label () {
+        #Prevent overdriving Kubernetes infra, don't set activity state to same as previous state
+        previous_state=`cat $3`
+        if [ "${2}" = "${previous_state}" ]; then
+          echo "`date` INFO: ${APP}-Current and Previous state match, not updating label"
         else
-          echo "`date` WARN: ${APP}-Setting return code NOT_READY for ${pod_name}"
+          echo ${2} > ${3}
+          echo "[{\"op\": \"add\", \"path\": \"/metadata/labels/${1}\", \"value\": \"${2}\" }]" > /tmp/patch_label.json
+          KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
+          curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" --request PATCH --data "$(cat /tmp/patch_label.json)" \
+              -H "Content-Type:application/json-patch+json" \
+              https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/$STATEFULSET_NAMESPACE/pods/$HOSTNAME
         fi
-        return ${return_code}
+      }
+
+      # note that there are no re-tries here, if check fails the return not ready.
+      APP=`basename "$0"`
+      version=${1}
+
+      password=`cat /mnt/disks/secrets/username_admin_password`
+      return_code=0
+      state_file=/tmp/activity_state
+      if [ ! -f ${state_file} ]; then
+        echo "State file not found, creating!"
+        echo "false" > ${state_file}
+      fi
+      echo "`date` INFO: ${APP}-node oridinal"
+      IFS='-' read -ra host_array <<< $(hostname)
+      node_ordinal=${host_array[-1]}
+
+      if [ "${node_ordinal}" = "2" ]; then
+        echo "`date` INFO: ${APP}-Monitor node ready check"
+        # Note that when dealing with Monitor, only need to be concerned and readiness response.
+        # active label will always be "false"
+        echo "`date` INFO: ${APP}-For monitor node just check for 3 online nodes in group"
+        role_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
+                -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><group/></redundancy></show></rpc>" \
+                -c "/rpc-reply/rpc/show/redundancy/group-node/status[text() = \"Online\"]"`
+        if [ `echo ${role_results} | jq '.countSearchResult' -` -eq 3 ]; then
+          echo "`date` INFO: ${APP}-Monitor node is redundancy ready"
+          exit 0
+        else
+          echo "`date` INFO: ${APP}-Monitor node is not redundancy ready, result: ${role_results}"
+          exit 1
+        fi
+      fi # End Monitor Node
+
+      health_result=`curl -s -o /dev/null -w "%{http_code}"  http://localhost:5550/health-check/guaranteed-active`
+      
+      case "${health_result}" in
+        "200")
+           echo "`date` INFO: ${APP}-Message Router is Active and Healthy"
+          set_label "active" "true" $state_file
+          exit 0
+          ;;
+        "503")
+          set_label "active" "false" $state_file
+          if (( "$version" < 7 )); then
+           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, this is K8S 1.6 ready"
+           exit 0
+          else
+           echo "`date` INFO: ${APP}-Message Router is Healthy and not Active, further check required"
+          fi
+          ;;
+        "")
+          echo "`date` WARN: ${APP}-Unable to deturmine config role, failing readiness check"
+          set_label "active" "false" $state_file
+          exit 1
+      esac
+       
+      echo "`date` INFO: ${APP}-Checking if Message Router is Standby"
+      case "${node_ordinal}" in
+        "0")
+          config_role="primary"
+          ;;
+        "1")
+          config_role="backup"
+          ;;
+      esac
+      online_results=`/mnt/disks/solace/semp_query.sh -n admin -p ${password} -u http://localhost:8080/SEMP \
+              -q "<rpc semp-version='soltr/8_5VMR'><show><redundancy><detail/></redundancy></show></rpc>" \
+              -v "/rpc-reply/rpc/show/redundancy/virtual-routers/${config_role}/status/activity[text()]"`
+      local_activity=`echo ${online_results} | jq '.valueSearchResult' -`
+      echo "`date` INFO: ${APP}-Local activity state is: ${local_activity}"
+      case "${local_activity}" in
+        "\"Local Active\"")
+          echo "`date` INFO: ${APP}-Redundancy is up locally Active"
+          # Set active label to "true"
+          set_label "active" "true" $state_file
+          # Pass readiness check
+          exit 0
+          ;;
+        "\"Mate Active\"")
+          echo "`date` INFO: ${APP}-Redundancy is up mate Active"
+          # Set active label to "false"
+          set_label "active" "false" $state_file
+          # Pass readiness check
+          exit 0
+          ;;
+        *)
+          echo "`date` WARN: ${APP}-Redundancy not up or not responding, failing readiness check"
+          # Set active label to "false"
+          set_label "active" "false" $state_file
+          # Fail readiness check
+          exit 1
+          ;;
+      esac
 
 
     semp_query.sh: |-
@@ -112,11 +195,16 @@ objects:
             echo  '{"errorInfo":"missing parameter"}'
             exit 1
           fi
-        query_response=`curl -u ${name}:${password} ${url} -d "${query}"`
+        query_response=`curl -sS -u ${name}:${password} ${url} -d "${query}"`
+        # Validate first char of response is "<", otherwise no hope of being valid xml
+        if [[ ${query_response:0:1} != "<" ]] ; then 
+          echo "`date` ERROR: ${APP}-${script_name}: Query failed, non-xml response -${query_response}-" >&2
+          exit 1
+        fi
         query_response_code=`echo $query_response | xmllint -xpath 'string(/rpc-reply/execute-result/@code)' -`
 
         if [[ -z ${query_response_code} && ${query_response_code} != "ok" ]]; then
-            echo "`date` ERROR: ${APP}-${script_name}: Query failed -${query_response}-" >&2
+            echo "`date` ERROR: ${APP}-${script_name}: Query failed, bad return code -${query_response}-" >&2
             echo  "{\"errorInfo\":\"query failed -${query_response_code}-\"}"
             exit 1
         fi
@@ -136,7 +224,6 @@ objects:
             exit 0
         fi
 
-# Source: solace/templates/storageClass.yaml
 - kind: StorageClass
   apiVersion: storage.k8s.io/v1
   metadata:
@@ -146,7 +233,7 @@ objects:
   #Default don't set zone or zones, allow k8s to strip across active zones
     type: gp2
 
-# Source: solace/templates/service-discovery.yaml
+
 - kind: Service
   apiVersion: v1
   metadata:
@@ -167,7 +254,6 @@ objects:
       app: solace
       release: "${DEPLOYMENT_NAME}"
 
-# Source: solace/templates/service.yaml
 - kind: Service
   apiVersion: v1
   metadata:
@@ -192,8 +278,8 @@ objects:
     selector:
       app: solace
       release: "${DEPLOYMENT_NAME}"
+      active: "true"
 
-# Source: solace/templates/solaceStatefullSet.yaml
 - kind: StatefulSet
   apiVersion: apps/v1beta1
   metadata:
@@ -231,8 +317,10 @@ objects:
           readinessProbe:
             initialDelaySeconds: 30
             periodSeconds: 5
-            tcpSocket:
-              port: 8080
+            exec:
+              command:
+              - /mnt/disks/solace/readiness_check.sh
+              - "6"
           securityContext:
             privileged: true
             capabilities:
